
server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PizzaAuthService
    username: root
    password: ROot
    driver: com.mysql.cj.jdbc,Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: Pizza-Auth-Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
    fetchRegistry: true
    registerWithEureka: true